export const phrases = [
  "You cannot pass all cultures through the same filter.",
  "One system cannot be expected to present all cultures as they wish, or even as they are.",
  "Google translate homogenises the self and the other on the assumption that all utterances are interchangeable.",
  "Oral traditions are alien to computers by design; created within cultures who hold the written word as sacrosanct.",
  "Is the internet a form of cultural imperialism?",
  "Not all cultures speak—or wish to speak—the language of contracts and corporations.",
  "Cultural imperialism is forcing another group to use your system.",
  "You cannot force inclusion. People and cultures have the right to remain at arms length.",
  "Not all cultures choose to write. Perhaps some choose to remain ephemeral.",
  "Helping another begins by understanding their desires, not presenting your current method as their solution.",
  "Forcing the language of money and finance on others supercharges cultural imperialism under the guise of inclusion and support.",
  "Technological monopolies enforce cultural imperialism, in communication and the dissemination of information.",
  "To code for the internet you must write in Maths and English.",
  "Computational methods, from Facebook to code, force all cultures to fit themselves into a handful of methods developed, largely, by an other.",
  "Cultural imperialism is a dark spectre of the internet age.",
  "The tools we use each day serve up imperialism, on a global scale.",
  "The spoken word is flexible, text is concrete. Both have their place.",
  "Can all utterances be reduced to the multi-dimensional points within a neural network?",
  "Meaning changes when it is passed between both people and computers, but with notably different effectst",
  "This message will slowly decay on each translation. Google translate doesn't grasp its meaning, only its form and likeness.",
  "The internet is a tool, not a culture. Yet its code and protocols are forged in the image of just a handful of dominant cultures.",
  "Lanugage is far more than a string of words and letters.",
  "Translation and auto‑correct punishes dialects which deviate from a ‘standard’ grammar.",
  "Language detection defaults to the most common script, utterance and form in its dataset.",
  "Automated localization glosses over the hard-to-translate, promising false equivalence in culture and worldview.",
  "Spelling and grammar checkers shame non‑native constructions into uniformity.",
  "AI chatbots parrot stereotypes learned from the loudest, richest data silos.",
  "Online translators erase cultural boundaries, at the demand of the service provider.",
  "Closed platforms bury cultural knowledge in black boxes; open protocols can keep it alive.",
  "Who can stop a language being entered into a database? Who can ensure it is correctly represented?",
  "Google translate is an AI laced in the legacy of labour extracted from low-paid gig workers across the globe.",
  "True representation demands more than token inclusion. Google Translate degrades meaning, refracting voices through a corporate lens.",
  "Google translate's lanaguage select implies equality, but it is clear that some languages are more equal than others.",
];
